services:
  db:
    image: postgres:16-alpine
    container_name: rimal_db
    restart: always
    environment:
      POSTGRES_USER: rimal
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: rimal_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rimal -d rimal_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: rimal_api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=rimal
      - DB_PASS=${db_password}
      - DB_NAME=rimal_db
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    depends_on:
       db :
         condition: service_healthy 

    volumes:
      # <--- ADDED: Enable "Hot Reload" / Live editing
      - ./backend:/usr/src/app # Syncs your local folder to container's workdir
      - /usr/src/app/node_modules # (If Node.js) Prevents overwriting container deps


volumes:
  postgres_data:
